language: node_js
node_js:
- node
notifications:
  email: false
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  override:
  - npm ci
  script:
  - npm start &
  - cypress run --record --key 86ce623b-9bbc-4993-8dca-f3535c528333
deploy:
  provider: vercel
  app: ozoneIQ
  skip_cleanup: true