language: node_js
node_js:
- node
notifications:
  email: false
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  override:
  - npm ci
  - npm run cy:verify
before_script:
  - npm start --silent &
script:
  - npm run start:ci &
  - cypress run --record --key 86ce623b-9bbc-4993-8dca-f3535c528333
  - kill $(jobs -p) || true