language: node_js
node_js:
- node
notifications:
  email: false
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  override:
  - npm ci
# if this file doesn't work, this branches option should be deleted before moving forward in trouble shooting
branches:
  only: 
    - main
# -------------------------------------
deploy:
  provider: vercel
  app: ozoneIQ
  skip_cleanup: true